---
  header_logo_url:
  header_logo_text: Cucujoidea World Catalog
  header_links:
    - label: Browse Catalog
      link: /otus/85891/overview
    
    - label: Home
      link: /

    - label: About
      link: /about
